[package]
name = "smith"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "npm for MCP. install, compose, secure, and manage MCP servers."

[[bin]]
name = "smith"
path = "bin/smith/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
smith-config = { path = "crates/config", version = "0.1.0" }
smith-compose = { path = "crates/compose", version = "0.1.0" }
smith-install = { path = "crates/install", version = "0.1.0" }
smith-secure = { path = "crates/secure", version = "0.1.0" }
smith-profile = { path = "crates/profile", version = "0.1.0" }
smith-registry = { path = "crates/registry", version = "0.1.0" }

[workspace]
members = [
    "crates/config",
    "crates/install",
    "crates/compose",
    "crates/secure",
    "crates/profile",
    "crates/registry",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
